
benchmark2:
  class: models.benchmark.Benchmark2
  params:
    booster: gbtree
    tree_method: hist
    max_depth: 8 
    learning_rate: 0.025
    objective: "multi:softprob"
    num_class: 2
    eval_metric: mlogloss
benchmark3:
  class: models.benchmark.Benchmark2
  params:
    booster: gblinear
    tree_method: hist
    max_depth: 8 
    learning_rate: 0.025
    objective: "multi:softprob"
    num_class: 2
    eval_metric: mlogloss