
benchmark:
  class: models.xgboost_model.XgboostModel
  params:
    booster: gbtree
    tree_method: hist
    max_depth: 8 
    learning_rate: 0.025
    objective: "multi:softprob"
    num_class: 2
    eval_metric: mlogloss
xgb_gblinear:
  class: models.xgboost_model.XgboostModel
  params:
    booster: gblinear
    tree_method: hist
    max_depth: 8 
    learning_rate: 0.025
    objective: "multi:softprob"
    num_class: 2
    eval_metric: mlogloss